project:
  type: website
  output-dir: docs

website: 
  title: Kate Laidlaw
  favicon: logos/KateLaidlaw.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Resume.qmd
      - Projects.qmd
      - About.qmd
  page-footer: 
    background: light
    left: Copyright 2025, Kate Laidlaw
    right: ESS 330, Quantitative Reasoning for Ecosystem Science and Sustainability
format:
  html:
    theme: sandstone
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#050606"
    linkcolor: "#125c22"
    monofont: courier new
    css: styles.css
    toc: true
    toc-location: right

