project:
  type: website
  output-dir: docs

website: 
  title: "KateLaidlaw.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Resume.qmd
      - Projects.qmd

format:
  html:
    theme: sandstone
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#050606"
    linkcolor: "#125c22"
    monofont: courier new
    css: styles.css
    toc: true
    toc-location: right

editor: visual

